image:
  file: .gitpod.Dockerfile

tasks:
  - init: 
      sudo apt-get update
      sudo apt-get install -y graphviz
      pip install context-mapper
vscode:
  extensions:
    - contextmapper.context-mapper-vscode-extension